### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by nodiscc** [DiSiqueira/Imgur#4]
```
$ dsimgur 'https://imgur.com/gallery/pv2ol' 
Traceback (most recent call last):
  File "/usr/local/bin/dsimgur", line 9, in <module>
    load_entry_point('DSImgur==1.0.0.2', 'console_scripts', 'dsimgur')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/DSImgur-1.0.0.2-py2.7.egg/DSImgur/__init__.py", line 11, in <module>
    from DSImgur import DSImgur
  File "/usr/local/lib/python2.7/dist-packages/DSImgur-1.0.0.2-py2.7.egg/DSImgur/DSImgur.py", line 113
    try:
       ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by Skylion007** [comment]
pip hasn't been updated and installing from pip still gives this issue.
